Repository kysect/Shreks, pull requests merged in 2022-09, with the labels that each got.

#277 Feat/isu update
  Source/Application/Kysect.Shreks.Application.Abstractions/Identity/IAuthorizationService.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Students/CreateStudent.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Users/Commands/UpdateUserUniversityId.cs
  Source/Application/Kysect.Shreks.Application.Dto/Users/StudentDto.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Students/CreateStudentHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Users/UpdateUserUniversityIdHandler.cs
  Source/Domain/Kysect.Shreks.Common/Exceptions/User/UserAlreadyHasAssociationException.cs
  Source/Domain/Kysect.Shreks.Core/UserAssociations/IsuUserAssociation.cs
  Source/Domain/Kysect.Shreks.Core/Users/Student.cs
  Source/Domain/Kysect.Shreks.Core/Users/User.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Extensions/ServiceCollectionExtensions.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Kysect.Shreks.Identity.csproj
  Source/Infrastructure/Kysect.Shreks.Identity/Services/AuthorizationService.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/UserProfile.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/StudentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociations/IsuUserAssociationGenerator.cs
  Source/Kysect.Shreks.WebApi/Controllers/AssignmentController.cs
  Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
  Source/Kysect.Shreks.WebApi/Controllers/GithubManagementController.cs
  Source/Kysect.Shreks.WebApi/Controllers/GroupAssignmentController.cs
  Source/Kysect.Shreks.WebApi/Controllers/StudentController.cs
  Source/Kysect.Shreks.WebApi/Controllers/StudyGroupController.cs
  Source/Kysect.Shreks.WebApi/Controllers/SubjectController.cs
  Source/Kysect.Shreks.WebApi/Controllers/SubjectCourseController.cs
  Source/Kysect.Shreks.WebApi/Controllers/SubjectCourseGroupController.cs
  Source/Kysect.Shreks.WebApi/Controllers/UserController.cs
  Source/Playground/Kysect.Shreks.Playground/Program.cs
  Source/Tests/Kysect.Shreks.Tests/Mapping/MappingTest.cs
Labels: requirement

#282 refactor: moved deadline policies from assignment to subject course
  Source/Application/Kysect.Shreks.Application/Extensions/FindDeadlinePolicyExtensions.cs
  Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/AssignmentConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourses/SubjectCourseConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/AssignmentTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/GroupAssignmentTest.cs
Labels: refactoring, area:domain

#316 fix: data import
  Source/Kysect.Shreks.WebApi/Controllers/UserController.cs
  Source/Playground/Kysect.Shreks.DataImport/Program.cs
  Source/Playground/Kysect.Shreks.DataImport/ShreksApiClient.cs
Labels: bug

#317 fix: update username
  Source/Application/Kysect.Shreks.Application.Handlers/Students/UpdateUserNameHandler.cs
  Source/Kysect.Shreks.WebApi/Controllers/UserController.cs
Labels: bug

#355 Фикс валидации пермишенов для команд
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionPointsHandler.cs
Labels: bug

#354 fix: subject course get 500
  Source/Application/Kysect.Shreks.Application.Handlers/Study/GetSubjectCoursesHandler.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/SubjectCourseProfile.cs
Labels: bug

#358 fix: case insensitive github username comparison
  Source/Domain/Kysect.Shreks.Core/Specifications/Github/FindUserByGithubUsername.cs
Labels: bug

#407 fix: deadline state ordering
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/AssignmentDeadlineStateEvaluator.cs
Labels: bug, area:domain

#412 feat: mark reviewed command
  Source/Application/Kysect.Shreks.Application.Commands/Commands/MarkReviewedCommand.cs
  Source/Application/Kysect.Shreks.Application.Commands/Processors/ShreksCommandProcessor.cs
Labels: task

#440 fix: state column width
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tables/QueueTable.cs
Labels: bug, area:google

#448 fix: table formatting
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
Labels: bug, area:google

#449 fix: table formatting
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
Labels: bug, area:google
