Repository kysect/Shreks, pull requests merged in 2022-08, with the labels that each got.

#54 Refactor/submission
  Source/Application/Kysect.Shreks.Application.Abstractions/DataAccess/IShreksDatabaseContext.cs
  Source/Domain/Kysect.Shreks.Core/Study/StudentAssignment.cs
  Source/Domain/Kysect.Shreks.Core/Study/Submission.cs
  Source/Domain/Kysect.Shreks.Core/ValueObject/Points.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/StudentAssignmentConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubmissionConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Context/ShreksDatabaseContext.cs
Labels: refactoring, task

#29 Feat: Google sheets
  Source/Application/Kysect.Shreks.Application.Abstractions/GoogleSheets/IGoogleTableAccessor.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Kysect.Shreks.Application.Abstractions.csproj
  Source/Domain/Kysect.Shreks.Core/Formatters/IUserFullNameFormatter.cs
  Source/Domain/Kysect.Shreks.Core/Formatters/UserFullNameFormatter.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Converters/ISheetRowConverter.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Converters/StudentPointsConverter.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Converters/SubmissionsConverter.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ColumnIndexExtensions.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/RowIndexExtensions.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetFactory.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetFactory.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/QueueSheetFactory.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/Ranges/DimensionRangeFactory.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/Ranges/GridRangeFactory.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Models/ColumnWidth.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Models/CreateSheetArguments.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Models/SheetDescriptor.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Models/SheetRange.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Models/StudentPointsArguments.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/SheetEnums/HorizontalAlignment.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/SheetEnums/UpdatedFields.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/SheetEnums/VerticalAllignment.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/ISheet.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/PointsSheet.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/QueueSheet.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/GoogleSheetCreator.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/GoogleTableEditor.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/client_secrets.json
Labels: task

#44 Feat: seeding
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
  Source/Domain/Kysect.Shreks.Core/Users/Mentor.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/GithubUserAssociationSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/GroupAssignmentSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/IsuUserAssociationSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/MentorSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/StudentGroupSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/StudentSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/SubjectCourseAssociationSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/SubjectCourseGroupSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/SubjectCourseSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/SubjectSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/SubmissionSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/DeadlinePolicy/DeadlinePolicyGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/GroupAssignmentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/StudentGroupGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/SubjectCourseAssociations/SubjectCourseAssociationGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/MentorGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/StudentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociations/GithubUserAssociationGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociations/IsuUserAssociationGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/Kysect.Shreks.Seeding.csproj.DotSettings
  Source/Tests/Kysect.Shreks.Tests/DataAccess/DataAccessTestBase.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/GroupAssignmentTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/StudentGroupTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubjectCourseAssociationTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubjectCourseGroupTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubjectCourseTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubjectTest.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubmissionTest.cs
Labels: task

#76 chore: webhooks configuration
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/IActionNotifier.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/AppBuilderExtensions.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubConfiguration.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/ShreksConfiguration.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs
  Source/Playground/Kysect.Shreks.Playground.Github/Kysect.Shreks.Playground.Github.csproj
  Source/Playground/Kysect.Shreks.Playground.Github/Program.cs
  Source/Playground/Kysect.Shreks.Playground.Github/appsettings.Development.json
Labels: area:github

#91 Refactor/mentor subject course relation
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourseGroup.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourseConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourseGroupConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubjectCourseGroupTest.cs
Labels: refactoring, area:domain

#106 Feat/queue
  Source/Application/Kysect.Shreks.Application.Abstractions/DataAccess/IShreksDatabaseContext.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/UpdateSubmissionDate.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/CreateSubmissionHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
  Source/Domain/Kysect.Shreks.Core/Models/ForwardIterator.cs
  Source/Domain/Kysect.Shreks.Core/Models/SortingOrder.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/AssignmentDeadlineStateEvaluator.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/ISubmissionEvaluator.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/SubmissionDateTimeEvaluator.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/SubmissionEvaluator.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/AssignmentGroupFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/GroupQueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/IQueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/QueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/IQueryExecutor.cs
  Source/Domain/Kysect.Shreks.Core/Queue/PositionedSubmission.cs
  Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
  Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
  Source/Domain/Kysect.Shreks.Core/Study/StudentGroup.cs
  Source/Domain/Kysect.Shreks.Core/Study/Submission.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/Filters/AssignmentGroupFilterConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/Filters/GroupQueueFilterConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/PositionedSubmissionConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/QueueFiltersConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/SubmissionEvaluatorsConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/SubmissionQueueConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Context/ShreksDatabaseContext.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/IDatabaseSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/StudentSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/StudentGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
  Source/Playground/Kysect.Shreks.Playground/Kysect.Shreks.Playground.csproj
  Source/Playground/Kysect.Shreks.Playground/Program.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/DataAccessTestBase.cs
  Source/Tests/Kysect.Shreks.Tests/DataAccess/SubmissionTest.cs
  Source/Tests/Kysect.Shreks.Tests/Kysect.Shreks.Tests.csproj
Labels: requirement, task, area:domain

#162 feat: submission code
  Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
  Source/Domain/Kysect.Shreks.Core/Specifications/Submissions/GetStudentAssignmentSubmissions.cs
  Source/Domain/Kysect.Shreks.Core/Submissions/GithubSubmission.cs
  Source/Domain/Kysect.Shreks.Core/Submissions/Submission.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Submissions/GithubSubmissionGenerator.cs
  Source/Playground/Kysect.Shreks.Playground/Program.cs
Labels: task, area:domain

#186 feat: submission state
  Source/Domain/Kysect.Shreks.Core/Models/SubmissionState.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/AssignmentGroupFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/GroupQueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubmissionQueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubmissionStateFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
  Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
  Source/Domain/Kysect.Shreks.Core/Study/StudentGroup.cs
  Source/Domain/Kysect.Shreks.Core/Submissions/Submission.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/QueueFiltersConfiguration.cs
Labels: task, area:domain

#189 Feat/submission state commands
  Source/Application/Kysect.Shreks.Application.Abstractions/Exceptions/UnauthorizedException.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/UpdateSubmissionState.cs
  Source/Application/Kysect.Shreks.Application.Commands/Commands/ActivateCommand.cs
  Source/Application/Kysect.Shreks.Application.Commands/Commands/DeactivateCommand.cs
  Source/Application/Kysect.Shreks.Application.Commands/Processors/IShreksCommandVisitor.cs
  Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
  Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionStateDto.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Google/GetSubjectCourseGroupSubmissionQueueHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionStateHandler.cs
  Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/ValueObjectsProfile.cs
  Source/Tests/Kysect.Shreks.Tests/Application/UpdateSubmissionStateHandlerTest.cs
  Source/Tests/Kysect.Shreks.Tests/Mapping/MappingTest.cs
Labels: task

#197 feat: calendar
  Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/AssignmentDeadlineStateEvaluator.cs
  Source/Domain/Kysect.Shreks.Core/Tools/Calendar.cs
  Source/Playground/Kysect.Shreks.Playground/Program.cs
Labels: requirement, task

#205 Feat/queue usage
  Source/Application/Kysect.Shreks.Application.Handlers/Google/GetSubjectCourseGroupSubmissionQueueHandler.cs
  Source/Application/Kysect.Shreks.Application/Extensions/ServiceCollectionExtensions.cs
  Source/Application/Kysect.Shreks.Application/Kysect.Shreks.Application.csproj
  Source/Application/Kysect.Shreks.Application/Tools/QueryExecutor.cs
  Source/Domain/Kysect.Shreks.Core/Kysect.Shreks.Core.csproj
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/GroupQueueFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubjectCourseFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubmissionStateFilter.cs
  Source/Domain/Kysect.Shreks.Core/Queue/PositionedSubmission.cs
  Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourseGroup.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/Filters/GroupQueueFilterConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/Filters/SubjectCourseFilterConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/PositionedSubmissionConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/SubmissionQueueConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourseAssociationConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourseGroupConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/SubmissionProfile.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
  Source/Kysect.Shreks.WebApi/Kysect.Shreks.WebApi.csproj
  Source/Kysect.Shreks.WebApi/Program.cs
  Source/Kysect.Shreks.sln
  Source/Playground/Kysect.Shreks.Playground.Github/Kysect.Shreks.Playground.Github.csproj
  Source/Playground/Kysect.Shreks.Playground.Github/Program.cs
  Source/Playground/Kysect.Shreks.Playground.Google/Kysect.Shreks.Playground.Google.csproj
  Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
  Source/Playground/Kysect.Shreks.Playground/Program.cs
Labels: task, area:domain

#234 fix: submission queue filter discriminator
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/QueueFiltersConfiguration.cs
Labels: bug

#235 Fix/deadline span conversion
  Source/Infrastructure/Kysect.Shreks.DataAccess/Context/ShreksDatabaseContext.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/ValueConverters/TimeSpanConverter.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/DeadlinePolicy/DeadlinePolicyGenerator.cs
Labels: bug

#237 Fix/user mentor student
  Source/Application/Kysect.Shreks.Application.Dto/Users/StudentDto.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Students/GetStudentByUserHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Validators/PermissionValidator.cs
  Source/Application/Kysect.Shreks.DataAccess.Abstractions/Extensions/DbSetExtensions.cs
  Source/Domain/Kysect.Shreks.Core/Specifications/GroupAssignments/GetStudentGroupAssignment.cs
  Source/Domain/Kysect.Shreks.Core/Specifications/Submissions/GetStudentAssignmentSubmissions.cs
  Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
  Source/Domain/Kysect.Shreks.Core/Users/Mentor.cs
  Source/Domain/Kysect.Shreks.Core/Users/Student.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/UserAssociations/GithubUserAssociationConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/UserAssociations/IsuUserAssociationConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/UserAssociations/UserAssociationConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/MentorConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/StudentConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/SubmissionProfile.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/MentorSeeder.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
  Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/MentorGenerator.cs
  Source/Tests/Kysect.Shreks.Tests/Application/GetCoursePointsBySubjectCourseHandlerTest.cs
  Source/Tests/Kysect.Shreks.Tests/Application/GetGithubUsernamesForSubjectCourseHandlerTest.cs
  Source/Tests/Kysect.Shreks.Tests/Application/UpdateSubmissionStateHandlerTest.cs
Labels: bug, area:domain

#236 Fix/date only conversion
  Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Github/GetCurrentUnratedSumbissionByPrNumberHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
  Source/Domain/Kysect.Shreks.Core/Specifications/Submissions/FindLatestGithubSubmission.cs
  Source/Domain/Kysect.Shreks.Core/Study/GroupAssignment.cs
  Source/Domain/Kysect.Shreks.Core/Submissions/Submission.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/Context/ShreksDatabaseContext.cs
  Source/Infrastructure/Kysect.Shreks.DataAccess/ValueConverters/DateOnlyConverter.cs
Labels: bug

#238 Fix/student user
  Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/StudentConfiguration.cs
Labels: bug

#250 Feat/identity
  Source/Application/Kysect.Shreks.Application.Abstractions/Identity/Commands/PromoteToAdmin.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Identity/Commands/Register.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Identity/Queries/GetIdentityUserByToken.cs
  Source/Application/Kysect.Shreks.Application.Abstractions/Identity/Queries/Login.cs
  Source/Application/Kysect.Shreks.Application.Dto/Identity/IdentityUserDto.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Identity/GetIdentityUserByTokenHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Identity/LoginHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Identity/PromoteToAdminHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Identity/RegisterHandler.cs
  Source/Application/Kysect.Shreks.Application.Handlers/Kysect.Shreks.Application.Handlers.csproj
  Source/Application/Kysect.Shreks.Application/Kysect.Shreks.Application.csproj
  Source/Application/Kysect.Shreks.DataAccess.Abstractions/Kysect.Shreks.DataAccess.Abstractions.csproj
  Source/Domain/Kysect.Shreks.Common/Exceptions/RegistrationFailedException.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Entities/ShreksIdentityRole.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Entities/ShreksIdentityUser.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Extensions/RoleManagerExtensions.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Extensions/ServiceCollectionExtensions.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Kysect.Shreks.Identity.csproj
  Source/Infrastructure/Kysect.Shreks.Identity/ShreksIdentityContext.cs
  Source/Infrastructure/Kysect.Shreks.Identity/Tools/IdentityConfiguration.cs
  Source/Infrastructure/Kysect.Shreks.Mapping/Kysect.Shreks.Mapping.csproj
  Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/IdentityProfiles.cs
  Source/Kysect.Shreks.WebApi/Controllers/IdentityController.cs
  Source/Kysect.Shreks.WebApi/Extensions/HttpContextExtensions.cs
  Source/Kysect.Shreks.WebApi/Filters/AuthenticationFilter.cs
  Source/Kysect.Shreks.WebApi/Models/AdminModel.cs
  Source/Kysect.Shreks.WebApi/Models/LoginRequest.cs
  Source/Kysect.Shreks.WebApi/Models/LoginResponse.cs
  Source/Kysect.Shreks.WebApi/Models/RegisterUserRequest.cs
  Source/Kysect.Shreks.WebApi/Program.cs
  Source/Kysect.Shreks.WebApi/appsettings.json
  Source/Kysect.Shreks.sln
Labels: task
